name: "blogify"
services:
  app:
    build:
      context: docker/app
      dockerfile: Dockerfile
    container_name: blogify
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
