name: "blogify"
services:
  users-http:
    build:
      context: docker/app
      dockerfile: Dockerfile
    volumes:
      - ./internal:/internal
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
    working_dir: /internal/users
    ports:
      - "127.0.0.1:3002:$PORT"
    environment:
      GOCACHE: /go-cache
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
